### ISSUE TITLE
TrayImage is Loading But stickers Are not Loading

### ISSUE THREAD

**Issue by hariiprasad** [meetpatel5720/WhatsAppStickerMaster#1]
@meetpatel5720 Hii.. thanks for your awesome code. But when i placed json file in Firebase only trayimage loading in app but not stickers. Can you resolve this?

**Comment by meetpatel5720** [comment]
Add this into your proguard-rules file
-keepclassmembers class com.android.mp.wastickermaster.** { *; }
If it does not solve your issue there may be a problem with your JSON structure. Let me know how you had organized data in your JSON file

**Comment by hariiprasad** [comment]
@meetpatel5720 
hiii i have placed it but problem still exists
here is my json
![screenshot 103](https://user-images.githubusercontent.com/42040267/52177807-92319980-27ec-11e9-91dd-65664d1a1f41.png)
![screenshot 104](https://user-images.githubusercontent.com/42040267/52177808-9362c680-27ec-11e9-994c-5b6f1e117535.png)

**Comment by meetpatel5720** [comment]
Try to debug and see that if url for all images are loading or not. If it
is loading than there may be problem with glide image loader.

**Comment by hariiprasad** [comment]
@meetpatel5720 is my json is correct?

**Comment by hariiprasad** [comment]
i just added my google services json file to project and added that stickers json to realtime database in firebase. is there any changes i need to do?

**Comment by meetpatel5720** [comment]
Json is correct.

**Comment by hariiprasad** [comment]
![screenshot 105](https://user-images.githubusercontent.com/42040267/52178684-87303680-27f7-11e9-84b2-94b3839effd1.png)

@meetpatel5720 iam getting this bro

**Comment by hariiprasad** [comment]
@meetpatel5720 do i need to change anything?

**Comment by meetpatel5720** [comment]
For some reason, URL for stickers are not loading and glide model is getting null URL. Can you show me your whole code with whatever change you had made?

**Comment by hariiprasad** [comment]
Broo.. i didnt changed anything i just removed your google services json and added my google services json to the project and uploaded the stickers json in firebase realtime database.

**Comment by hariiprasad** [comment]
@meetpatel5720 and i placed stickers raw links in json that are located in github

**Comment by hariiprasad** [comment]
i also  checked by placing stickers links that are located in firebase storage also. But didnt worked.

**Comment by hariiprasad** [comment]
@meetpatel5720  here is the json file that i uploaded in firebase realtime database

{
  "android_play_store_link": "https://play.google.com/store/apps/details?id=com.example.example",
  "ios_app_store_link": "",
  "sticker_packs": [
    {
      "identifier": "1",
      "name": "example",
      "publisher": "hari",
      "tray_image_file": "https://raw.githubusercontent.com/hariiprasad/my-personal/master/icon.png",
      "publisher_email":"hariprasad@gmail.com",
      "publisher_website": "",
      "privacy_policy_website": "",
      "license_agreement_website": "",
      "stickers": [
        {
          "image_file": "https://raw.githubusercontent.com/hariiprasad/my-personal/master/st1.webp",
          "emojis": ["??"]
        },
        {
          "image_file": "https://raw.githubusercontent.com/hariiprasad/my-personal/master/st12.webp",
          "emojis": ["??"]
        },
        {
          "image_file": "https://raw.githubusercontent.com/hariiprasad/my-personal/master/st13.webp",
          "emojis": ["??"]
        }
      ]
    }
  ]
}

**Comment by hariiprasad** [comment]
@meetpatel5720  if i placed your google services json,iam successfully getting your stickers packs... can you plz send screenshot of your json file example or if possible file?

**Comment by meetpatel5720** [comment]
Either you change "image_file" to "sticker_url" in JSON or change the name of "sticker_url" string variable to "image_file". I think now it will work for you :)

**Comment by hariiprasad** [comment]
@meetpatel5720 thanks broo... it worked!

**Comment by hariiprasad** [comment]
@meetpatel5720  the app keeps crashing when i click on add symbol and when i click on add to whatsapp button app is restarting. Help!

**Comment by hariiprasad** [comment]
@meetpatel5720 now the stickers are loading but app keep crashing when i click on add symbol or add to whatspp button. Again its working with your google services json. Help needed! bro

**Comment by hariiprasad** [comment]
@meetpatel5720 will be waiting for your reply😀

**Comment by hariiprasad** [comment]
@meetpatel5720 prob solved!!! thank you!

**Comment by meetpatel5720** [comment]
XXXXXXXXXXX0622-01-08-2021to03-09-2021.pdf
